# consul服务端口号
server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  # consul 注册中心
  cloud:
    consul:
      host: localhost
      prot: 8500
      # hostname: 127.0.0.1
      server-name: ${spring.application.name}