server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh1 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001   #匹配后提供服务的路由地址 地址不能写死
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - After=2020-03-14T23:42:40.803+08:00[GMT+08:00] # 配置访问时间 必须要在这个时间之后才能访问
#            - Cookie=username,dl # 必须带这这个cookie 不然访问不了 curl http://localhost:9527/payment/lb --cookie "username=dl"
#            - Header=X-Request-Id, \d+ # 请求头X-Request-Id的属性 并且值为整数的正则表达式

eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provider 注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
