server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos 服务注册中心地址
    sentinel:
      transport:
        #配置 Sentinel dashboard 地址 8080将会监控 8401
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource:
        ds1:  # 数据源1
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service # 微服务名称用作配置Id
            groupId: DEFAULT_GROUP #默认分组
            data-type: json # 数据类型
            rule-type: flow #流控规则类型

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持



